spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: Alicenguyen!
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
